# Generated by Django 5.2.17 on 2026-08-26 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_selection'),
        ),
    ]
