# Generated by Django 5.2.17 on 2026-09-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_codesubmission_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='algorithm_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='algorithm_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='code_quality_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='code_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='overall_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='space_complexity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='space_complexity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='time_complexity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='time_complexity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
